### ISSUE TITLE
Problem with file type.

### ISSUE THREAD

**Issue by Webtakeme** [joshpeng/Sublime-Babel-VSCode#12]
For some reason when this extension activated there is incorrect icons on some files.

For example:
1. On ".js" file got icon for ReactJS (whery annoying - when you work on some non react project but all you ".js" files highlighted like "react")
2. On ".css" files got icon for PostCSS

> Incorrect "class" on file.

Was tested on windows and linux (both - code and code-insiders) on different computer.
Problem appear on different icon themes.

![type-file-icon](https://cloud.githubusercontent.com/assets/14540860/24753374/86d6f682-1ada-11e7-9cc7-4eaaca67c562.jpg)

**Comment by joshpeng** [comment]
I use vscode-icons by Roberto and don't seem to run into these issues.
