### ISSUE TITLE
Sublime-Babel-VSCode breaks vscode-ext-color-highlight

### ISSUE THREAD

**Issue by GollyJer** [joshpeng/Sublime-Babel-VSCode#13]
Just wanted to report that [vscode-ext-color-highlight](https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight) completely stops working when Sublime-Babel-VSCode is enabled.

Sublime-Babel-VSCode stays because it's more awesome. But I'd love to have both working. :-D

**Comment by joshpeng** [comment]
Hello, I also use that color highlight extension, but it works on my end. It seems they recently updated too. Not sure if updating to the latest version makes a difference on your end or not.

![image](https://cloud.githubusercontent.com/assets/22549127/24978344/2cba17d8-1f85-11e7-94f5-17eb54c4da8d.png)

My Color Highlight version is 2.0.1 and my VSCode version is 1.11.1.

**Comment by GollyJer** [comment]
Ha!  Look what updated when I opened vscode today!

![2017-04-12_16h42_16](https://cloud.githubusercontent.com/assets/689204/24978733/b62500cc-1f9f-11e7-9505-3b2b85715d8f.png)

Everything working together now. 👍
