### ISSUE TITLE
Backtick support

### ISSUE THREAD

**Issue by jbrodriguez** [joshpeng/Sublime-Babel-VSCode#16]
This issue (https://github.com/Microsoft/vscode/issues/20338), made me disable all extensions then enable them one by one until I found that this extension is causing the behaviour reported there:

"... when I type a backtick, I only get one, not two. That's pretty much it."

Any idea how to fix this ?

**Comment by joshpeng** [comment]
In your ```%USERPROFILE%\.vscode\extensions``` folder, find the ```joshpeng.sublime-babel-vscode-0.2.5``` folder. From there, open ```language-configuration.json``` in a text editor.

Add this to ```["`", "`"]``` to the ```autoClosingPairs``` and ```surroundingPairs``` sections after line 20 and 28 respectively. Remember to add a comma on the line above where you add the backtick pair.

**Comment by jbrodriguez** [comment]
Awesome @joshpeng ! That did it !

Will you add this in your next release ?
