### ISSUE TITLE
Opening .js file it uses JavaScript React (Babel)

### ISSUE THREAD

**Issue by svipben** [joshpeng/Sublime-Babel-VSCode#18]
Hello,

when I'm opening .js file it uses JavaScript React (Babel) language mode, not JavaScript (babel).

**Comment by joshpeng** [comment]
If you don't like .js files to open as ```JavaScript React (Babel)```, in the ```package.json``` file in ```C:\Users\Josh\.vscode\extensions\joshpeng.sublime-babel-vscode-0.2.5``` remove line 44 should change that for you.
