### ISSUE TITLE
auto indent in jsx syntax

### ISSUE THREAD

**Issue by hirosuke999** [joshpeng/Sublime-Babel-VSCode#2]
Hi.

I have a feature request.

The sublime's babel plugin can do auto indent when inserting new line with cursor is located inside jsx tag.
Could you consider to implement same feature? I think it must be very helpful.

Thanks.

**Comment by joshpeng** [comment]
@hirosuke999 Hm. I'm not quite sure which scenario you mean.

Using this code snippet from the React [docs](https://facebook.github.io/react/docs/jsx-in-depth.html#specifying-the-react-element-type) discussing JSX tags...
```
import React from 'react';
import CustomButton from './CustomButton';

function WarningButton() {
  // return React.createElement(CustomButton, {color: 'red'}, null);
  <CustomButton color="red" />;
}
```
When I press enter inside the <CustomButton> tag I do get the new line auto indented in both Sublime and VS Code. Can you please provide an example of what you mean? Thanks.

**Comment by hirosuke999** [comment]
@joshpeng Thanks for your quick reply and sorry for my obscure explanation.

I mean HTML tag in js or jsx files, like  `<div></div>` or `<ul></ul>`

I provided an example. Please check these followings. Thanks.

```
/*------------------------------------------
 * Case of Sublime's babel plugin.
/*------------------------------------------*/

// before press enter.
const Product = React.createClass({
  render: function () {
    return (
      <div>{**the cousor is located here**}</div>
    );
  }
}

// After press enter.
const Product = React.createClass({
  render: function () {
    return (
      <div>
        {**the cousor will be located here**}
      </div>
    );
  }
}
```

```
/*------------------------------------------
 * Case of this plugin.
/*------------------------------------------*/

// before press enter.
const Product = React.createClass({
  render: function () {
    return (
      <div>{**the cousor is located here**}</div>
    );
  }
}

// After press enter.
const Product = React.createClass({
  render: function () {
    return (
      <div>
      {**the cousor will be located here**}</div>
    );
  }
}
```

**Comment by joshpeng** [comment]
@hirosuke999 Hmmm. I can't seem to reproduce this. Maybe it has to do with some of your other VS Code settings?

Please see this video: [https://zippy.gfycat.com/IllfatedAstonishingIndiancow.webm](https://zippy.gfycat.com/IllfatedAstonishingIndiancow.webm)
Sublime is on the left, VS Code is on the right

**Comment by hirosuke999** [comment]
@joshpeng Thanks for providing the video. So I see. Seems you're right.

OK. I'm going to check other VS code settings.

Thank you for your kind correspondence.
