### ISSUE TITLE
[insiders] auto indent in jsx syntax

### ISSUE THREAD

**Issue by orangemooncreative** [joshpeng/Sublime-Babel-VSCode#20]
- VSCode Version: Version 1.13.0-insider (1.13.0-insider)
- OS Version: Sierra 10.12.5

My cursor is not placed in the correct position on enter.

![screen recording 2017-06-04 at 02 24 pm](https://cloud.githubusercontent.com/assets/1316656/26797011/7452427a-49f9-11e7-862a-eecbd8be48fa.gif)

**Comment by joshpeng** [comment]
Please let me know if latest sources fixes it for you. You can also try adding the highlighted line in the image below to this extension's ```package.json``` file.

![image](https://cloud.githubusercontent.com/assets/22549127/26799286/c55b0c0c-49e9-11e7-8a4e-e8f7f5d9b50d.png)

**Comment by orangemooncreative** [comment]
@joshpeng updating the package.json file worked. thanks.

**Comment by joshpeng** [comment]
Actually this change seems to not have the desired effect so I've reverted it. It actually causes the extension to be disabled. I will try and investigate deeper when I have a little more time.

**Comment by orangemooncreative** [comment]
@joshpeng ok thanks. i originally posted it there (#28005) but was told i needed to submit the issue with you. hopefully it can get straightened out.

**Comment by joshpeng** [comment]
@orangemooncreative I just released a version that should have it resolved. Please let me know if it works for you too. Thanks!
