### ISSUE TITLE
Color syntax in arrow functions

### ISSUE THREAD

**Issue by kv4sha** [joshpeng/Sublime-Babel-VSCode#21]
Wrong color syntax in arrow functions without body.
![capture](https://user-images.githubusercontent.com/13916346/26868279-19db61cc-4b71-11e7-87f5-005bf962af27.PNG)

**Comment by joshpeng** [comment]
It depends on which color theme you are using. This is what it looks like with my [One Dark](https://marketplace.visualstudio.com/items?itemName=joshpeng.theme-onedark-sublime) theme on VSCode as well as compared against Atom.

![image](https://user-images.githubusercontent.com/22549127/26891856-4f8f5fa4-4b6b-11e7-9b22-e4394cc9910c.png)

**Comment by kv4sha** [comment]
I'am using [One Dark (Sublime Babel)](https://github.com/joshpeng/Charcoal-Oceanic-Next) 
This problem is present only in classes

![capture](https://user-images.githubusercontent.com/13916346/26917122-ad0e7e2e-4c35-11e7-9376-12dc97b95f72.PNG)

**Comment by joshpeng** [comment]
In ```sublime-babel.json```, after [Line 344](https://github.com/joshpeng/Sublime-Babel-VSCode/blob/master/syntaxes/sublime-babel.json#L344), add this:

```
{ "include": "#literal-language-variable"},
{ "include": "#literal-function-call"},
```
Please try that out and let me know if it breaks anything for you within classes.

**Comment by kv4sha** [comment]
Thanks, that's helped.
Also I noticed one more issue. It is not connected with bug above.
![capture](https://user-images.githubusercontent.com/13916346/27023860-0668d526-4f5d-11e7-96b7-348b3029a808.PNG)
Sorry if this is the way it should be.

**Comment by joshpeng** [comment]
That one is expected. The regex inside grammar rules can only act on one line at a time.
