### ISSUE TITLE
color < > symbols in JSX/HTML tags the same as tag names

### ISSUE THREAD

**Issue by Talor-A** [joshpeng/Sublime-Babel-VSCode#23]
Hi, is there a way to have the < > and </ /> symbols around HTML/JSX elements colored the same as the component name / tag name? 

in this ![screenshot](https://raw.githubusercontent.com/joshpeng/Sublime-Babel-VSCode/master/images/babel-es6.png) you can see that the < > brackets are blue and I'm trying to see if there's a way to make them red. Perhaps this is a problem with the color theme, but it irks me slightly that they're different colors. thanks a lot for this great extension too.

**Comment by joshpeng** [comment]
That should be adjustable in the individual themes themselves on the ```punctuation.definition.tag``` scopes.
