### ISSUE TITLE
Emmet expansion seems to break when enabling SublimeBabel

### ISSUE THREAD

**Issue by jtokoph** [joshpeng/Sublime-Babel-VSCode#25]
Example code:
```
import React from 'react';

export default class Test extends React.Component {
  render() {
    return (
      .foo
    );
  }
}
```
If I expand the .foo with emmet, it works fine and I end up with:
```
import React from 'react';

export default class Test extends React.Component {
  render() {
    return (
      <div className="foo"></div>
    );
  }
}
```

If I then try to expand another time inside like so:
```
import React from 'react';

export default class Test extends React.Component {
  render() {
    return (
      <div className="foo">
        .bar
      </div>
    );
  }
}
```
Emmet won't expand the `.bar`

If I disable SublimeBabel, the `.bar` expansion works as expected

**Comment by jtokoph** [comment]
I forgot to include some configuration information:

I have the following emmet related configuration options set:
```
{
  "emmet.syntaxProfiles": {
    "javascript": "jsx"
  },
  "emmet.showExpandedAbbreviation": "never",
  "emmet.showAbbreviationSuggestions": false
}
```

It seems like removing the last two configuration options I can at least get the suggested expansions to work, but using a bound hot key or manually invoking the expand abbreviation action from the command pallet still won't work.

**Comment by joshpeng** [comment]
Hi @jtokoph Try removing all emmet config settings. It seems to work on my end with nothing configured for it.

**Comment by joshpeng** [comment]
Please reopen if you still have issues.

**Comment by EQuimper** [comment]
Hey @joshpeng I just get the same error like @jtokoph . I try removing all the emmets config but that still break. My first component can get trigger by emmet tab. But the second one never. But if I disable this package all work like suppose. :s Any idea what I can do for making work ?
