### ISSUE TITLE
Emmet expansion doesnt work inside nested tags

### ISSUE THREAD

**Issue by ramya-rao-a** [joshpeng/Sublime-Babel-VSCode#26]
@joshpeng 

See https://github.com/Microsoft/vscode/issues/34750

The reason the Emmet command doesnt work is because Emmet doesnt recognize the language insde the nested tags which is `jsx-sublime-babel-tags`

Emmet works if the language under the cursors is either
1. One of the supported modes OR
2. Is mapped to one of the supported modes in the `emmet.includeLanguages` setting OR
3. The scopename for the language Inherits from one of the supported modes.

We made it work for the embedded language in vue using option 3
with this change: https://github.com/vuejs/vetur/commit/49f722db3193fea9dd938c1638f8c15a640666c3
Since `vue-html` (which is an embedded language) now inherits from html, the `Emmet: Expand Abbreviation` will work out of the box.

Thoughts on doing something similar for `jsx-sublime-babel-tags`?

**Comment by joshpeng** [comment]
@ramya-rao-a Hm. I'm not quite sure I understand the original issue because on my end I am able to emmet expand inside nested tags without doing any changes.

**Comment by ramya-rao-a** [comment]
Try custom components and not the common html elements
And use the `Emmet: Expand Abbreviation` command

**Comment by joshpeng** [comment]
@ramya-rao-a Thanks for the report and assistance. I believe it is fixed now by setting the tag back to `jsx-tags`.

**Comment by ramya-rao-a** [comment]
Interesting... what prompted to name it `jsx-sublime-babel-tags`?

**Comment by joshpeng** [comment]
@ramya-rao-a There was something I was trying to get differing block/line comments in JSX tags, but then realized that JSX only uses block comments. That was probably a relic from that experimentation that I thought was inconsequential to have named differently.
