### ISSUE TITLE
Object key color should not match string color

### ISSUE THREAD

**Issue by nhuesmann** [joshpeng/Sublime-Babel-VSCode#33]
Object keys are the same color as strings, making objects containing many string values hard to read. Example:

![screen shot 2018-05-18 at 2 19 39 pm](https://user-images.githubusercontent.com/613922/40258459-8b6f2aae-5aa6-11e8-9998-f8edb1cc1559.png)

I am using [Sublime-Babel-VSCode](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) with [Charcoal Oceanic Next](https://marketplace.visualstudio.com/items?itemName=joshpeng.theme-charcoal-oceanicnext). I wasn't sure if this was an issue with this extension or the other, so I'm going to leave this on both. Is there a workaround for this? Thanks!

**Comment by joshpeng** [comment]
For that particular theme you can see it uses the same color for key-value pairs in the last screenshot on the theme page. You should be able to change it however you want though. Just add a definition for the `string.unquoted.label` scope in the tmTheme.
