### ISSUE TITLE
Sublime Babel by Josh Peng is not longer available. 3

### ISSUE THREAD

**Issue by fgoksu** [joshpeng/Sublime-Babel-VSCode#39]
When I go to Babel documentation and look for the Sublime Babel link, it doesn't work and gives me and 404 error. The VSCode Extension manager doesn't find the plugin neither.

![image](https://user-images.githubusercontent.com/47495420/72268394-0510da80-3622-11ea-9633-fc2cad708043.png)
![image](https://user-images.githubusercontent.com/47495420/72268405-0a6e2500-3622-11ea-8218-4a0a70280f90.png)

**Comment by javajosh** [comment]
Confirmed.

**Comment by EricEsajian** [comment]
Search: Oceanic Next (Sublime Babel) in the extenstion instead of Josh Peng or Sublime Babel.

**Comment by hadrysmateusz** [comment]
I can also confirm. And it's a shame, it was the best one around.

**Comment by EricEsajian** [comment]
confirmed. This has been discontinued unfortunately.

**Comment by dakshkhetan** [comment]
:(

**Comment by joshpeng** [comment]
Sorry, you guys can just download it from the Github release page and drop it into wherever you have `.vscode/extensions` folder.

**Comment by enhuichang** [comment]
Confirmed

**Comment by yinkatona** [comment]
Confirmed

**Comment by yinkatona** [comment]
Confirmed
