### ISSUE TITLE
Syntax highlighting broken when using ES6 arrow function's implicit return to return JSX

### ISSUE THREAD

**Issue by matthamil** [joshpeng/Sublime-Babel-VSCode#4]
*From https://github.com/Microsoft/TypeScript-TmLanguage/issues/401*

- VSCode Version: 1.8.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Create a `.js` file, and write some JSX in it like so:

![image](https://cloud.githubusercontent.com/assets/11802078/21708284/94d486f8-d39c-11e6-91ec-2ef1149e5b1a.png)

2. Use an arrow function to implicitly return JSX.

3. Watch as the syntax highlighting below breaks.

This only breaks when the JSX is implicitly returned with the ES6 arrow function. If you wrap the JSX in parens, the syntax highlighting is not broken:

![image](https://cloud.githubusercontent.com/assets/11802078/21708312/d0693b00-d39c-11e6-899b-fe611387f394.png)

Using the arrow function and using an explicit return fixes the syntax highlighting as well:

![image](https://cloud.githubusercontent.com/assets/11802078/21708329/fa3fa860-d39c-11e6-83b5-eadaf5b76bd1.png)

**Comment by joshpeng** [comment]
@matthamil Thanks for the report. Which color theme are you using?

**Comment by matthamil** [comment]
@joshpeng https://marketplace.visualstudio.com/items?itemName=joshpeng.theme-charcoal-oceanicnext

**Comment by joshpeng** [comment]
@matthamil This was pretty nasty. I committed a potential fix to the ```arrow-implicit-return``` branch. Can you please try it out locally on your end and provide feedback? To test, you can grab the [```sublime-babel.json```](https://github.com/joshpeng/Sublime-Babel-VSCode/blob/arrow-implicit-return/syntaxes/sublime-babel.json) file and replace the current version in your VS Code extensions folder.

Windows: ```%USERPROFILE%\.vscode\extensions\joshpeng.sublime-babel-vscode-0.2.3\syntaxes```
Mac/Linux: ```~/.vscode/extensions/joshpeng.sublime-babel-vscode-0.2.3/syntaxes```

**Comment by matthamil** [comment]
:tada: I think that fixed it

**Comment by joshpeng** [comment]
Aw crap. Just noticed it doesn't fully work when two or more tags are used.

**Comment by joshpeng** [comment]
@matthamil Did another commit. Can you please try again? Something like this should have all the tags highlighted the same color now. If you run across any other scenarios where this might be broken please let me know. Thanks.

```org => <UserOrganizationItemContainer><Blah><zxclk>fdsa</zxclk></Blah></UserOrganizationItemContainer>```

**Comment by matthamil** [comment]
It works unless you nest the same type of element like so:

The first example is nesting 3 `<div>` tags. The second example nests varied tags.

![image](https://cloud.githubusercontent.com/assets/11802078/21745175/c1ffc328-d4ea-11e6-850f-d20e09e4e8de.png)

**Comment by joshpeng** [comment]
@matthamil Pushed another commit. Please try again. Thanks for all the testing help.
[```sublime-babel.json```](https://github.com/joshpeng/Sublime-Babel-VSCode/blob/arrow-implicit-return/syntaxes/sublime-babel.json)

**Comment by matthamil** [comment]
Sure thing, thanks for maintaining this project :tada:. All seems to be working now. If another bug comes up, I'll open another issue.

**Comment by joshpeng** [comment]
@matthamil One last time haha. I reverted the previous commit and put in another approach. Fingers crossed. The earlier issue was leaking tokens and messing up closing ) and } brackets.
