### ISSUE TITLE
Comenting JSX

### ISSUE THREAD

**Issue by xDae** [joshpeng/Sublime-Babel-VSCode#9]
<img width="688" alt="captura de pantalla 2017-02-13 a las 13 13 50" src="https://cloud.githubusercontent.com/assets/6037190/22883130/f3501006-f1ee-11e6-992e-2869c66d12c1.png">

comenting JSX manually is a pain 😅

**Comment by joshpeng** [comment]
Commenting is done by VSC directly, not this grammar per se.

You can select the lines you want and press Ctrl+/ to comment them out in one shot.
Alternatively, you can also set a block comment hot key. I have mine set to Ctrl+Shift+/

```
{ "key": "ctrl+shift+/",           "command": "editor.action.blockComment",
                                     "when": "editorTextFocus && !editorReadonly" }
```
If you are referring to something else, can you please clarify? Thanks.

**Comment by xDae** [comment]
i meant, when i comment the code with the keys, is wrong inside JSX syntax

now:
<img width="403" alt="captura de pantalla 2017-02-15 a las 9 34 03" src="https://cloud.githubusercontent.com/assets/6037190/22966378/40363110-f362-11e6-8b01-21769fd22850.png">

correct:
<img width="435" alt="captura de pantalla 2017-02-15 a las 9 35 48" src="https://cloud.githubusercontent.com/assets/6037190/22966390/493ff7aa-f362-11e6-9090-930b470a202e.png">

**Comment by joshpeng** [comment]
Unfortunately that doesn't seem to be something that can be changed with grammar in VS Code. The commenting is handled outside of the grammar in ```language-configuration.json```, but that has no concept of context.
